directory: {{MUSIC_LIBRARY_DIR}}
library: {{APP_STATE_DIR}}/beets/musiclibrary.db

import:
  copy: no
  move: yes
  write: yes
  quiet: yes
  quiet_fallback: asis
  timid: no
  resume: yes
  incremental: no
  autotag: yes
  singletons: yes
  duplicate_action: skip
  log: {{APP_STATE_DIR}}/logs/beets-import.log

paths:
  default: $albumartist/$album%aunique{}/$track $title
  singleton: $albumartist/%if{$album,$album,Singles}/%if{$track,$track ,}$title

replace:
  '[<>:\?\*\|]': _
  '["]': _
  '[\\/]': _
  '[\x00-\x1f]': _
  '\s+$': ''
  '^\s+': ''

clutter:
  - Thumbs.DB
  - .DS_Store

ignore_hidden: yes
