--extractor-args
youtube:player_client=web_music
--concurrent-fragments
4
--write-subs
--sub-format
lrc/elrc/txt
--sub-langs
*orig,-live_chat
--convert-subs
lrc
-f
ba/bestaudio/best
-x
--audio-format
aac
--replace-in-metadata
album,playlist_title,artist,creator,track,title
:
-
--replace-in-metadata
title,creator
"(\(|\[).*(\)|\])"
""
--replace-in-metadata
title
"^[^-]+ - "
""
--parse-metadata
%(release_date,upload_date).4s:(?P<meta_date>.+)
--parse-metadata
%(track_number,playlist_index)s:%(track_number)s
--embed-metadata
--write-info-json
--convert-thumbnails
png
--ppa
"ThumbnailsConvertor+ffmpeg_o:-c:v png -vf crop='if(gt(ih,iw),iw,ih)':'if(gt(iw,ih),ih,iw)'"
--embed-thumbnail
